baseURL = "/"
title = "Manabu.tech"
theme = "hugo-notepadium"
copyright = "©2020 Manabu tech."

languageCode = "ja"
hasCJKLanguage = true

enableRobotsTXT = true

# Enable Disqus
#disqusShortname = "XXX"

# Google Analytics
googleAnalytics = "UA-92916914-1"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[params]
style = "auto"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
dateFormat = "Monday, January 2, 2006"  # if unset, default is "2006-01-02"
logo = ""  # if you have a logo png
slogan = "Power of your smile"
license = ""  # CC License
addThis = "ra-5e240e9fd4f629c7"

[params.comments]
enable = false  # En/Disable comments globally, default: false. You can always enable comments on per page.

[params.math]
enable = false  # optional: true, false. Enable globally, default: false. You can always enable math on per page.
use = "katex"  # option: "katex", "mathjax". default: "katex"

[params.syntax]
use = "none"  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "dracula"
darkTheme = "xcode-dark"  # apply this theme in dark mode

[permalinks]
posts = "/:year/:month/:filename/"

[params.nav]
showCategories = true       # /categories/
showTags = true             # /tags/

# custom navigation items

[[params.nav.custom]]
title = "Categories"
url = "/categories"

[[params.nav.custom]]
title = "Tags"
url = "/tags"


[[params.nav.custom]]
title = "About me"
url = "/about"

#[[params.nav.custom]]
#title = "ins0 inc."
#url = "https://ins0.jp/"

#[[params.nav.custom]]
#title = "tsumugu.inc"
#url = "https://www.tsumugu-inc.com"

