version: 2
jobs:
    docker:
      #- image: cibuilds/hugo:0.53
    environment:
      #- GOCACHE: "/tmp/go/cache"
    steps:
checkout:
  post:
    - git submodule sync
    - git submodule update --init --recursive

machine:
  timezone: Asia/Tokyo

dependencies:
  pre:
    - go get -v github.com/cntrump/hugo-notepadium
    - git config --global user.name "CircleCI"
    - git config --global user.email "circleci@example.com"

deployment:
  master:
    branch: master
    commands:
      - git clone git@github.com:gakuji-t/gakuji-t.github.io.git public
      - hugo
      - cd public && git add .
      - cd public && git commit -m "[ci skip] publish"
      - cd public && git push origin master
